# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74a3560cd0f0aa9cb8d5c8cf2ffd020e8056cc6ccc8cff8ef9b630b467ebe0df12c8d057ea57f353c804fa7f33be230958a833736a55722bd32c03454862df1b

test:
  secret_key_base: fbe8fc2e1ec4140033d3360079eebeedb8ad2690107e52bb45af06dc57883bc4700cf2d67cacb8aeb0c18e8ebcdc66bb0884bfac7eb789f3e2d465ea2487d1a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  DB_HOST: rd1jz5briekjpa6.cebs6q1r2inq.ap-northeast-1.rds.amazonaws.com
  DB_NAME: RailsSampleApp
  S3_BUCKET_NAME: railssampleapp-s3bjs4i-d68ri1z2nmfd
  AWS_REGION: ap-northeast-1